class ReportsController < ApplicationController  
  before_action :logged_in
  before_action :admin_or_standard


  #reports/donor
  def donor
      respond_to do |format|
        
        #reports/donor.html request renders reports.html.erb
        format.html
        
        #reports/donor.csv
        format.csv { 
          headers = ["FIRST", "SPOUSE", "LAST", "ADDRESS", "TOWN", 
                    "STATE", "ZIP", "E-MAIL","DATE DONATED", "ITEMS DONATED"]
                    
          attributes = %w{donor_first_name donor_first_name donor_last_name address
                          donor_city state donor_zip donor_email date item_notes}
      
          csvFile = CSV.generate(headers: true) do |csv|
            csv << headers
            Day.all.each do |d|
              if  d.date.year.to_s ==  params[:date][:year] && d.date.mon.to_s == params[:date][:month]
                d.pickups.all.each do |p|
                  csv << attributes.map{ |attr| p.send(attr) }
                end
              end
            end
          end
          send_data csvFile, filename: 
          "donor_#{month_name(params[:date][:month])}#{params[:date][:year]}.csv"
        }
      end
  end

  #reports/truck
  def truck
    respond_to do |format|
      
      #reports/truck.html
      format.html {
        
        #Query returns the current and future dates only in ascending order. 
        #Used to populate the dropdown menu in the truck report form. 
        @days =  Day.where("date >= ?", Date.today).order('date ASC')
      } 
      
      #reports/truck.csv
      format.csv {
        
        #Query returns all the pickups for the given date. 
        pickups = Pickup.joins(:day).where("date = ?", params[:pickupday])
        
        #Sends csv file to the browser with the name addresses.csv. File is
        #genearted by the to_routes_csv function inside our Pickup model. 
        send_data pickups.to_routes_csv, filename: "addresses.csv"
      }
      
      #reports/truck.pdf
      format.pdf {
        
        #Query returns all the pickups for the given date.
        pickups = Pickup.joins(:day).where("date = ?", params[:pickupday])
        
        #Sends pdf file to the browser with the name pickups.pdf. File is
        #generated by the to_pdf function inside our Pickup model. Takes the
        #date as an argument.
        send_data pickups.to_pdf(params[:pickupday]), filename: 'pickups.pdf', 
        type: "application/pdf"
      }
    end
  end
  
  def month_name(number)
    case number
    when "1"
      return "jan"
    when "2"
      return "feb"
    when "3"
      return "mar"
    when "4"
      return "apr"
    when "5"
      return "may"
    when "6"
      return "jun"
    when "7"
      return "jul"
    when "8"
      return "aug"
    when "9"
      return "sep"
    when "10"
      return "oct"
    when "11"
      return "nov"
    when "12"
      return "dec"
    end
  end
end